#!/bin/bash/

echo "Learning of variables and arguments"

kalyan=mandapakala
ashini=ullipalem

if ($kalyan -eq mandapakala); then 
echo "kalyan located in mandapakala"

else "kalyan related to some other village"
fi